// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pidctstmpphlkpnndrcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZGN0c3RtcHBobGtwbm5kcmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODY0MTQsImV4cCI6MjA2NTA2MjQxNH0._UfhZWpu4lHhqJrhWdRqkJu8-dW3eUPxH2zLA_0bvEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);